# -*- coding: utf-8 -*-
"""
/***************************************************************************
 osm2wikipedia
                                 A QGIS plugin
 Convert .osm.pbf dump to geopackage with Wikipedia map styles
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-26
        copyright            : (C) 2021 by Artem Svetlov
        email                : trolleway@yandex.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load osm2wikipedia class from file osm2wikipedia.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .osm2wikipedia import osm2wikipedia
    return osm2wikipedia(iface)
